### ISSUE TITLE
'Datetime' Column Not Converting to datetime for Data Cleaning

### ISSUE THREAD

**Issue by atmcmillon** [atmcmillon/UFO_Sightings_Project#1]
#ufodf['datetime'] = ufodf['datetime'].dt.strftime('%d-%m-%Y %H:%M')

is the current code. It runs this error:

Traceback (most recent call last):
  File "/home/austin/UFOSightingProject/ufosightingsus.py", line 20, in <module>
    ufodf['datetime'] = ufodf['datetime'].dt.strftime('%d-%m-%Y %H:%M')
  File "/usr/lib/python3.7/site-packages/pandas/core/generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
  File "/usr/lib/python3.7/site-packages/pandas/core/accessor.py", line 187, in __get__
    accessor_obj = self._accessor(obj)
  File "/usr/lib/python3.7/site-packages/pandas/core/indexes/accessors.py", line 338, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values

**Comment by atmcmillon** [comment]
I want to actually leave this open for Hacktoberfest participants to practice or find other ways of implementing the 'datetime' and 'date posted' columns to a 'datetime 'series.
